spring:
  datasource:
    url: jdbc:mysql://mysqldb.c3esu4c2kctu.ap-northeast-2.rds.amazonaws.com:3306/hello
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
springdoc:
  use-fqn: true
