spring:
  profiles:
    default: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: update
    ai:
      openai:
        api-key: ${OPENAI_API_KEY}
      chat:
        memory:
          repository:
            jdbc:
              initialize-schema: never
    messages:
      encoding: UTF-8
  springdoc:
    use-fqn: true